### PR TITLE
Obtain a write lock before retrieving and deserializing an object

### PR DESCRIPTION
**Pull request by daines**
Test and possible fix for https://jira.duraspace.org/browse/FCREPO-1284

### CODE REVIEW

**Comment by barmintor** [comment]
I'm getting some test failures when I merge this branch into 3.8.1-SNAPSHOT. I'm assuming that mvn verify was passing for you before, so I'll try to figure out what might have happened in the meantime.

**Comment by barmintor** [comment]
(though if you have time to look at it that would be a great help!)

**Comment by sprater** [comment]
I did a clone and rebuild of Fedora from UNC's fork, read-write-lock branch;  I haven't yet attempted a merge with 3.8.1-SNAPSHOT.

I also run into the test failures in integration test A.  See https://gist.github.com/fc44a8eb4aaccb9307c5.git

Testing and building master from the UNC fork of fcrepo3 completes successfully, indicating a problem with the read-write-lock branch?

@daines, can you replicate the failure?  I'm running the tests on a RHEL6 Linux host, Java Sun 8.

**Comment by barmintor** [comment]
Just on a lark, I added a check to your patched DefaultDOManager:
```java
    /**
     * Gets a writer on an existing object.
     */
    @Override
    public DOWriter getWriter(boolean cachedObjectRequired, Context context,
            String pid) throws ServerException, ObjectLockedException {
        if (cachedObjectRequired) {
            throw new InvalidContextException(
                    "A DOWriter is unavailable in a cached context.");
        } else {
            BasicDigitalObject obj = new BasicDigitalObject();
            getWriteLock(pid);
            boolean clean = false;
            try {
                m_translator.deserialize(m_permanentStore.retrieveObject(pid), obj,
                    m_defaultStorageFormat, m_storageCharacterEncoding,
                    DOTranslationUtility.DESERIALIZE_INSTANCE);
                DOWriter w =
                    new SimpleDOWriter(context, this, m_translator,
                            m_defaultStorageFormat, m_storageCharacterEncoding,
                            obj);
                clean = true;
                return w;
            } finally {
                if (!clean) releaseWriteLock(pid);
            }
        }
    }
```
... and the test failures stopped. Is it possible that some pids are being left locked in an error state?

**Comment by barmintor** [comment]
Closing in favor of #26 for correct upstream branch.

**Pull request closed without merging**
